### ISSUE TITLE
Error: release example failed: secrets "example-keycloak-http" already exists

### ISSUE THREAD

**Issue by darylrobbins** [Activiti/activiti-cloud-charts#52]
Following instructions from https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud#getting-started-with-activiti-cloud

When running:
`helm install --name example activiti-cloud-charts/activiti-cloud-full-example --set global.gateway.domain=example.cloud`

I receive:

`Error: release example failed: secrets "example-keycloak-http" already exists`

**Comment by csckcac** [comment]
helm install --name example activiti-cloud-charts/activiti-cloud-full-example --version 1.1.4 --set global.gateway.domain=192.168.99.100.nip.io

this works for me

**Comment by darylrobbins** [comment]
Thanks, that works.
